# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 107d4b48fd3dca7a3b3c7808107c6162966b5abcf0a534eeb89cb95394dac905258d0fe97414b7533beb6d722fbaa14fc136d2391e901c8874af8acf13473fad

test:
  secret_key_base: 99d236235c2bb4b850bd0f245143811776f79cb44d66a2e111b7681ae5630d3a2860c42b3a2fb6715f3ac5fd9c8933c372ccc858988ddfb02609156c1c5e2f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
